# -*- coding: utf-8 -*-
"""data_config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4i2yEv56ngQlaITNfa-OusnibfwXKeM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile data_config.py
# # This module stores the raw datasets for the application
# # Time steps represent minutes relative to class start: -30 to 30
# TIME_STEPS = [-30, -20, -10, 0, 10, 20, 30]
# 
# # Traffic intensity values per 10 minutes
# CAMPUS_DATA = {
#     '1': {
#         'name': "IOH Main Campus",
#         'traffic': [10, 15, 25, 30, 23, 15, 10],
#         'peak': 30
#     },
#     '2': {
#         'name': "MC Mong Kok",
#         'traffic': [5, 8, 15, 25, 20, 5, 3],
#         'peak': 25
#     },
#     '3': {
#         'name': "JCC Jockey Club",
#         'traffic': [6, 9, 18, 28, 25, 10, 5],
#         'peak': 28
#     }
# }