# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4i2yEv56ngQlaITNfa-OusnibfwXKeM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from models import IOHModel, MCModel, JCCModel
# from data_config import CAMPUS_DATA
# 
# def main():
#     # Polymorphism: Different objects stored in a dictionary (Self-study Data Structure)
#     models = {
#         '1': IOHModel(CAMPUS_DATA['1']['name']),
#         '2': MCModel(CAMPUS_DATA['2']['name']),
#         '3': JCCModel(CAMPUS_DATA['3']['name'])
#     }
# 
#     while True:
#         print("\n" + "="*45)
#         print("   HKMU CAMPUS TRAFFIC SYSTEM (v2.0)")
#         print("="*45)
#         print("1. IOH")
#         print("2. MC")
#         print("3. JCC")
#         print("4. Exit")
# 
#         choice = input("\nSelect building (1-3) or 4 to Exit: ")
# 
#         if choice == '4':
#             print("System Exited. Thank you.")
#             break
# 
#         if choice in models:
#             # Training using the peak value from data_config
#             current_model = models[choice]
#             current_model.train_model(CAMPUS_DATA[choice]['peak'])
# 
#             # Input Validation for range -30 to 30
#             while True:
#                 try:
#                     user_min = int(input("Enter minutes from class start (-30 to 30): "))
#                     if -30 <= user_min <= 30:
#                         break
#                     print("Error: Please stay within the range of -30 to 30.")
#                 except ValueError:
#                     print("Error: Input must be a whole number.")
# 
#             # Display Result
#             prediction = current_model.predict(user_min)
#             print(f"\n>>> Location: {current_model._campus_name}")
#             print(f">>> Predicted Traffic Intensity: {prediction:.2f}")
# 
#             # Visualization Choice
#             if input("\nShow the trend graph? (y/n): ").lower() == 'y':
#                 current_model.plot_trend(user_min)
#         else:
#             print("Invalid Selection. Try again.")
# 
# if __name__ == "__main__":
#     main()
