# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4i2yEv56ngQlaITNfa-OusnibfwXKeM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models.py
# from abc import ABC, abstractmethod
# import matplotlib.pyplot as plt
# import numpy as np
# 
# class HKMUBaseModel(ABC):
#     """Abstraction: Abstract Base Class defining the campus model interface"""
#     def __init__(self, campus_name):
#         self._campus_name = campus_name  # Encapsulation: Protected attribute
#         self._a = 0.0
#         self._c = 0.0
# 
#     @abstractmethod
#     def train_model(self, peak_val):
#         """Self-study Algorithm: Quadratic Fitting interface"""
#         pass
# 
#     def predict(self, x):
#         """Encapsulation: Internal logic for y = ax^2 + c"""
#         val = (self._a * (x**2)) + self._c
#         return max(0, val)
# 
#     def plot_trend(self, target_min):
#         """Visualization: Graphing the non-linear trend"""
#         time_range = np.linspace(-30, 30, 100)
#         predictions = [self.predict(t) for t in time_range]
# 
#         plt.figure(figsize=(10, 5))
#         plt.plot(time_range, predictions, color='forestgreen', linewidth=2, label='Traffic Flow')
#         plt.scatter([target_min], [self.predict(target_min)], color='red', s=100, zorder=5, label='User Input')
# 
#         plt.title(f"HKMU Traffic Analysis: {self._campus_name}")
#         plt.xlabel("Minutes from Class Start (0 = Peak)")
#         plt.ylabel("Traffic Intensity")
#         plt.axvline(x=0, color='black', linestyle='--', alpha=0.3, label='Class Start')
#         plt.xlim(-30, 30)
#         plt.grid(True, linestyle=':', alpha=0.6)
#         plt.legend()
#         plt.show()
# 
# class CampusQuadratic(HKMUBaseModel):
#     """Inheritance: General implementation of the self-study algorithm"""
#     def train_model(self, peak_val):
#         # Algorithm: Quadratic curve y = ax^2 + c
#         # We solve for 'a' so that traffic is near zero at +/- 30 mins
#         self._c = peak_val
#         self._a = - (peak_val / 900)
#         print(f"Algorithm: {self._campus_name} trained using Quadratic Regression.")
# 
# class IOHModel(CampusQuadratic): pass
# class MCModel(CampusQuadratic): pass
# class JCCModel(CampusQuadratic): pass