# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VgcrRg84g2reV0kMlRgkS7yhDdVQXMbg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import math

# ------------------------------
# Class for the Model (Figure part)
# ------------------------------
class ElevatorFlowModel:
    def __init__(self, seed=42):
        self.seed = seed
        self.data = None
        self.model = None
        self.X = None
        self.y = None

    def generate_data(self):
        """Generate synthetic elevator passenger flow data."""
        np.random.seed(self.seed)
        time = np.arange(-15, 16, 1)  # -15 to +15 minutes
        # Symmetric quadratic peaked at time=0, ensuring positive flow
        flow_true = 60 - 0.2 * time**2
        flow = flow_true + np.random.normal(0, 5, size=len(time))
        self.data = pd.DataFrame({'time_min': time, 'passenger_flow': flow})
        return self.data

    def train(self):
        """Train a linear regression model on the data."""
        if self.data is None:
            self.generate_data()
        self.X = self.data[['time_min']]
        self.y = self.data['passenger_flow']
        self.model = LinearRegression()
        self.model.fit(self.X, self.y)
        return self.model

    def predict(self, time_input):
        """Predict flow for a given time (minutes relative to lesson start)."""
        if self.model is None:
            self.train()
        return self.model.predict([[time_input]])[0]

    def evaluate(self):
        """Compute MSE and R²."""
        if self.model is None:
            self.train()
        predictions = self.model.predict(self.X)
        mse = mean_squared_error(self.y, predictions)
        r2 = self.model.score(self.X, self.y)
        return mse, r2

    def plot(self, threshold=45):
        """Plot the data and regression line."""
        if self.model is None:
            self.train()
        time_smooth = np.linspace(self.X.min(), self.X.max(), 100).reshape(-1, 1)
        flow_smooth = self.model.predict(time_smooth)

        plt.figure(figsize=(10,6))
        plt.scatter(self.data['time_min'], self.data['passenger_flow'],
                    alpha=0.7, label='Observed flow')
        plt.plot(time_smooth, flow_smooth, color='red', linewidth=2,
                 label='Regression line')
        plt.axvline(x=0, color='gray', linestyle='--',
                    label='Lesson start (10:00)')
        plt.axhline(y=threshold, color='orange', linestyle=':',
                    label=f'Threshold ({threshold})')
        plt.xlabel('Time relative to lesson start (minutes)')
        plt.ylabel('Passenger flow (people/min)')
        plt.title('HKMU Elevator Passenger Flow Near Lesson Time')
        plt.legend()
        plt.grid(True)
        plt.show()

# ------------------------------
# Class for the User Interface (User part)
# ------------------------------
class ElevatorFlowApp:
    def __init__(self):
        self.model = ElevatorFlowModel()

    @staticmethod
    def volume_of_sphere(radius):
        """Calculate volume of a sphere (from Lab 3)."""
        return round((4.0/3.0) * math.pi * radius**3, 2)

    @staticmethod
    def area_of_triangle(length, height):
        """Calculate area of a triangle (from Lab 3)."""
        return (length * height) / 2.0

    @staticmethod
    def quadratic_roots(a, b, c):
        """Find roots of quadratic equation (from Lab 3)."""
        if a == 0:
            raise ValueError("Not a quadratic: a must be non-zero")
        d = b**2 - 4*a*c
        if d < 0:
            raise ValueError("No real roots (negative discriminant)")
        root1 = (-b + math.sqrt(d)) / (2*a)
        root2 = (-b - math.sqrt(d)) / (2*a)
        return root1, root2

    def run_full_analysis(self):
        """Generate data, train, predict, evaluate, and plot."""
        print("\n--- Generating Data ---")
        data = self.model.generate_data()
        print("Data sample:")
        print(data.head())
        print(f"\nTime range: {data['time_min'].min()} to {data['time_min'].max()} minutes")
        print(f"Flow range: {data['passenger_flow'].min():.1f} to {data['passenger_flow'].max():.1f} people/min")

        print("\n--- Training Model ---")
        model = self.model.train()
        print(f"Intercept (β₀): {model.intercept_:.2f}")
        print(f"Coefficient for time (β₁): {model.coef_[0]:.2f}")

        # Get user time
        try:
            user_time = float(input("\nEnter time relative to lesson start (e.g., -5, 0, 10): "))
        except ValueError:
            user_time = 0
            print("Invalid input, using time 0.")

        predicted = self.model.predict(user_time)
        print(f"Predicted flow at time {user_time}: {predicted:.2f} people/min")

        threshold = 45
        if predicted >= threshold:
            print("🚶‍♂️🚶‍♀️🚶 High flow: A lot of people expected!")
        else:
            print("🙂 Low to moderate flow.")

        print(f"\nEquation: passenger_flow = {model.intercept_:.2f} + ({model.coef_[0]:.2f}) * time_min")

        mse, r2 = self.model.evaluate()
        print(f"\nMean Squared Error (MSE): {mse:.2f}")
        print(f"R² score: {r2:.4f}")

        print("\n--- Plotting ---")
        self.model.plot(threshold)
        input("\nPress Enter to continue...")

    def demo_lab_functions(self):
        """Demonstrate the lab example functions."""
        print("\n--- Lab Functions Demo ---")
        print(f"Volume of sphere with radius 5: {self.volume_of_sphere(5)}")
        print(f"Area of triangle (length=3, height=4): {self.area_of_triangle(3, 4)}")
        try:
            r1, r2 = self.quadratic_roots(1, -3, 2)
            print(f"Quadratic roots of x² - 3x + 2: {r1}, {r2}")
        except ValueError as e:
            print(e)
        input("\nPress Enter to continue...")

    def custom_prediction(self):
        """Allow user to input a time and see prediction (without re‑generating)."""
        print("\n--- Custom Prediction ---")
        # Train model if not already done
        if self.model.model is None:
            print("Training model first...")
            self.model.train()

        # Show model info
        print(f"Model coefficients:")
        print(f"Intercept (β₀): {self.model.model.intercept_:.2f}")
        print(f"Coefficient for time (β₁): {self.model.model.coef_[0]:.2f}")

        try:
            user_time = float(input("\nEnter time relative to lesson start (e.g., -5, 0, 10): "))
        except ValueError:
            user_time = 0
            print("Invalid input, using time 0.")

        predicted = self.model.predict(user_time)
        print(f"Predicted flow at time {user_time}: {predicted:.2f} people/min")

        threshold = 45
        if predicted >= threshold:
            print("🚶‍♂️🚶‍♀️🚶 High flow: A lot of people expected!")
        else:
            print("🙂 Low to moderate flow.")
        input("\nPress Enter to continue...")

    def run(self):
        """Main menu loop."""
        while True:
            print("\n" + "="*40)
            print("   ELEVATOR PASSENGER FLOW PREDICTION")
            print("="*40)
            print("1. Run full analysis (generate, train, predict, evaluate, plot)")
            print("2. Demonstrate lab functions")
            print("3. Make a custom prediction (enter time)")
            print("4. Exit")
            print("\nHint: Try times near 0 (e.g., -5, 0, 5) to see high flow.")
            choice = input("Enter your choice (1-4): ").strip()

            if choice == '1':
                self.run_full_analysis()
            elif choice == '2':
                self.demo_lab_functions()
            elif choice == '3':
                self.custom_prediction()
            elif choice == '4':
                print("Goodbye!")
                break
            else:
                print("Invalid choice, please try again.")
                input("\nPress Enter to continue...")

# ------------------------------
# Run the application
# ------------------------------
if __name__ == "__main__":
    app = ElevatorFlowApp()
    app.run()